name: pytest-uv

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run build

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv venv --python ${{ matrix.python-version }}

      - name: Install graphviz-anywidget
        run: |
          # Install minimal dependencies for testing
          uv pip install -e ".[dev]"

      - name: Run pytest
        run: |
          source .venv/bin/activate
          pytest
